# Generated by Django 3.1 on 2021-01-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_meal_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meal_total',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AddField(
            model_name='order',
            name='no_of_meal',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_meal',
            field=models.CharField(default='', max_length=111),
        ),
    ]
